CFLAGS		+=	-O3 -lbz2

PREFIX		?=	/usr/local
INSTALL_PROGRAM	?=	${INSTALL} -c -s -m 555
INSTALL_MAN	?=	${INSTALL} -c -m 444

all:		bsdiff
bsdiff:		bsdiff.c

install:
	${INSTALL_PROGRAM} bsdiff ${PREFIX}/bin